language: generic
# Dependency of the minted package
before_install:
    - sudo apt-get install texlive-full
install:
    - pdflatex 00_master.tex
before_deploy:
      - git config --local user.name "Travis"
      - git config --local user.email "mail@felixstrobel.de"
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG
deploy:
    provider: releases
    api_key: $GITHUB_TOKEN
    file: ./00_master.pdf
    skip_cleanup: true
