language: generic

os: linux
dist: focal

jobs:
    include:
        - stage: install dependencies
          before_install:
          - sudo apt-get -y install libfontconfig1-dev libgraphite2-dev libharfbuzz-dev libicu-dev libssl-dev zlib1g-dev cargo ttf-dejavu
          install:
          - cargo install tectonic
          before_script:
          - wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/JetBrainsMono.zip
          script:
          - mkdir -p $HOME/.local/share/fonts/JetBrainsMono
          - unzip -d $HOME/.local/share/fonts/JetBrainsMono JetBrainsMono.zip
          - fc-cache -f -v
        - stage: compile
          script:
          - $HOME/.cargo/bin/tectonic main.tex
        - stage: deploy to github
          deploy:
            provider: releases
            token: $GITHUB_TOKEN
            file: ./main.pdf
            cleanup: true
            on:
                tags: true
