name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install Latex
      run: |
        apt-get install texlive-full
        pdflatex 00_master.tex
