name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install Latex
      run:  sudo apt-get install texlive-full
    - name: compile 00_master.tex
      run:  pdflatex 00_master.tex
